version: '2'

services:
  nginx:
    build:
      context: nginx/.
    ports:
      - 8080:80
    volumes:
      - ./Apps/static:/static
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres

